DROP TABLE quiz_questions;
DROP TABLE quizzes;
DROP TABLE questions;
DROP DATABASE quiz_app;
DEALLOCATE questions_by_subject;
DEALLOCATE questions_by_author;
DEALLOCATE questions_by_id;
DEALLOCATE questions_by_regex;
DEALLOCATE add_question;
DEALLOCATE delete_question;
DROP FUNCTION add_quiz(text, INTEGER, text, text[]);
DROP FUNCTION delete_quiz(text);
DEALLOCATE add_quiz(text, INTEGER, text, text[]);
DEALLOCATE delete_quiz(text);